### ISSUE TITLE
Not found :(

### ISSUE THREAD

**Issue by VClasic** [shade234sherif/fbhackver2.7#5]
Traceback (most recent call last):
  File "/home/kali/fbhackver2.7/brute2.py", line 38, in <module>
    z = browser.select_form(nr=1)
  File "/home/kali/mechanize/mechanize/_mechanize.py", line 681, in select_form
    raise FormNotFoundError("no form matching " + description)
mechanize._mechanize.FormNotFoundError: no form matching nr 1

**Comment by harkerbyte** [comment]
kindly re-install the tool now...
