### ISSUE TITLE
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/fbhackver2.7/brute.py", line 59, in <module>
    requests = web.open(urlopen)
               ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/mechanize/mechanize/_mechanize.py", line 257, in open
    data/data/com.termux/files/home/mechanize/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: b'request disallowed by robots.txt'

### ISSUE THREAD

**Issue by shahzaib62342** [shade234sherif/fbhackver2.7#8]
When giving Facebook profile link and hitting enter then this error receiving.

**Comment by harkerbyte** [comment]
Do you have a stable internet connection.
From what I'm seeing here... the problem is from your network connection.
403

**Comment by Hacker1hassan** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/fbhackver2.7/brute.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests' hey this error always pop up when I use python3 brute.py even my network is fast

**Comment by harkerbyte** [comment]
Run this command line `apt install requests`
Then try running the tool again.

**Comment by Jagger007irl** [comment]
> Run this command line `apt install requests`
> Then try running the tool again. 

Now it says
E: unable to locate package requests

**Comment by harkerbyte** [comment]
> > Run this command line `apt install requests`
> > Then try running the tool again. 
> 
> Now it says
> E: unable to locate package requests 

Install requests

> pip install requests

First make sure you have pip installed by running this command

> pip --version
